---
title: "space_titanic"
author: "Henry Luo"
date: "2023-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(psych)
library(gridExtra)
library(Metrics)
library(DescTools)
st.data <- read.csv("train.csv")
st.data <- replace(st.data, st.data == "", NA)

# st.data <- mutate(st.data, across(c(HomePlanet,CryoSleep,Destination,VIP,Transported), factor))

st.data <- separate(st.data, PassengerId, into = c("Group", "InGroupId"), sep = "_")
st.data <- separate(st.data, Cabin, into = c("Deck", "RoomNum", "Side"), sep = "/")

st.data$Group <- as.numeric(st.data$Group)
st.data$RoomNum <- as.numeric(st.data$RoomNum)


#sum(is.na(st.data))

#sum(rowSums(is.na(st.data)) > 0)/8693

st.data[, c("RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck")] <-
          lapply(st.data[, c("RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck")],  function(x) ifelse(is.na(x), 0, x))

st.data[, c("Deck", "Side")] <- lapply(st.data[, c("Deck", "Side")], function(x) ifelse(is.na(x), "NR", x))
st.data$RoomNum <- ifelse(is.na(st.data$RoomNum), -1, st.data$RoomNum)
st.data[, c("CryoSleep", "HomePlanet", "Destination","VIP", "Name")] <- 
  lapply(st.data[, c("CryoSleep", "HomePlanet", "Destination","VIP", "Name")], function (x) ifelse(is.na(x), "NR", x))

st.data$Age <- ifelse(is.na(st.data$Age), mean(na.omit(st.data$Age)), st.data$Age)



st.data <- mutate(st.data, across(c(HomePlanet,CryoSleep,Destination,VIP,Transported), factor))
st.data$InGroupId <- as.factor(st.data$InGroupId)
st.data$Deck <- as.factor(st.data$Deck)
st.data$Side <- as.factor(st.data$Side)
st.data$Side <- relevel(st.data$Side, ref = "P")

#st.data <- separate(st.data, Name, into = c("FirstName", "LastName"), sep = " ")
#st.data$LastName <- ifelse(is.na(st.data$LastName), "NR", st.data$LastName)
#st.data$family <- ifelse(duplicated(st.data$LastName) | duplicated(st.data$LastName, fromLast = TRUE), "Yes", "No")
#st.data$Family <- ifelse(duplicated(st.data[, c("Group", "LastName")]) | 
#                   duplicated(st.data[, c("Group", "LastName")], fromLast = TRUE), 
#                   "Yes", "No")
#st.data$Family <- as.factor(st.data$Family)
#st.data$FirstName <- as.factor(st.data$FirstName)
#st.data$LastName <- as.factor(st.data$LastName)

stage1.data <- st.data

```

```{r}
library(randomForest)
random.forest <- randomForest(Transported ~ .-Name -VIP-InGroupId, data = st.data, ntree = 1000)
varImpPlot(random.forest)
#threshold <- 0.5
pred <- predict(random.forest, type = 'class')
#predicted_class <- ifelse(pred > threshold, "True", "False") 

confusion_m <- table(st.data$Transported, pred)
misclass1 <- 1- sum(diag(confusion_m))/nrow(st.data)
misclass1

```

-Name -VIP-InGroupId-Destination: 0.1914184
.-Name -VIP-InGroupId-Destination-HomePlanet: 0.1938341


```{r}
#threshold <- 0.5
pred <- predict(random.forest, type = 'class')
#predicted_class <- ifelse(pred > threshold, "True", "False") 

confusion_m <- table(st.data$Transported, pred)
misclass1 <- 1- sum(diag(confusion_m))/nrow(st.data)
misclass1


```

original: 0.19497

nrun = 1000 : 0.1938341
nrun = 10000: 0.193604
-VIP, 1000: 0.1953296
-VIP,-Name, 1000:  0.1918785
-VIP,-Name-InGroupId, 1000: 0.1906131 ---sub1: 0.8017
-Name -VIP-InGroupId-Destination: 0.190153
-Name -VIP-InGroupId-Destination: 0.1914184
.-Name -VIP-InGroupId-Destination-HomePlanet: 0.1938341


```{r}

library(caret)

set.seed(123)
index <- createDataPartition(st.data$Transported, p = 0.7, list = FALSE, times = 1)
train_data <- st.data[index, ]
test_data <- st.data[-index, ]


```

```{r}
random.forest <- randomForest(Transported ~ .-Name -VIP-InGroupId, data = train_data, ntree = 1000)
pred <- predict(random.forest, type = 'class', newdata = test_data)


confusion_m <- table(test_data$Transported, pred)
misclass_cv2 <- 1-sum(diag(confusion_m))/nrow(test_data)
misclass_cv2
```
-Name -VIP-InGroupId-Destination-HomePlanet: 0.1894898


```{r}
st.data$route <- paste(st.data$HomePlanet, st.data$Destination)
st.data$route <- as.factor(st.data$route)
st.data <- separate(st.data, Name, into = c("FirstName", "LastName"), sep = " ")
st.data$LastName <- ifelse(is.na(st.data$LastName), "NR", st.data$LastName)
#st.data$family <- ifelse(duplicated(st.data$LastName) | duplicated(st.data$LastName, fromLast = TRUE), "Yes", "No")
st.data$Family <- ifelse(duplicated(st.data[, c("Group", "LastName")]) | 
                   duplicated(st.data[, c("Group", "LastName")], fromLast = TRUE), 
                   "Yes", "No")
st.data$Family <- as.factor(st.data$Family)

st.data$position <- as.factor(paste(st.data$Deck, st.data$Side))


```


```{r}
random.forest <- randomForest(Transported ~ .-FirstName-LastName -VIP-InGroupId-Deck-Side-HomePlanet-Destination-Family, data = st.data, ntree = 1000)
varImpPlot(random.forest)

pred <- predict(random.forest, type = 'class')


confusion_m <- table(st.data$Transported, pred)
misclass2 <- 1- sum(diag(confusion_m))/nrow(st.data)
misclass2

```


```{r}
set.seed(123)
index <- createDataPartition(st.data$Transported, p = 0.7, list = FALSE, times = 1)
train_data <- st.data[index, ]
test_data <- st.data[-index, ]

```

```{r}

random.forest <- randomForest(Transported ~ .-FirstName-LastName -VIP-InGroupId-Deck-Side-HomePlanet-Destination-Family, data = train_data, ntree = 1000)
pred <- predict(random.forest, type = 'class', newdata = test_data)


confusion_m <- table(test_data$Transported, pred)
misclass_cv2 <- 1-sum(diag(confusion_m))/nrow(test_data)
misclass_cv2
```
```{r}
test <- read.csv("test.csv")

test <- replace(test, test == "", NA)

# test <- mutate(test, across(c(HomePlanet,CryoSleep,Destination,VIP,Transported), factor))

test <- test %>%
  mutate(Group = sub("_.*$", "", PassengerId),
         InGroupId = sub("^.*_", "", PassengerId))
test <- separate(test, Cabin, into = c("Deck", "RoomNum", "Side"), sep = "/")

test$Group <- as.numeric(test$Group)
test$RoomNum <- as.numeric(test$RoomNum)


#sum(is.na(test))

#sum(rowSums(is.na(test)) > 0)/8693

test[, c("RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck")] <-
          lapply(test[, c("RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck")],  function(x) ifelse(is.na(x), 0, x))

test[, c("Deck", "Side")] <- lapply(test[, c("Deck", "Side")], function(x) ifelse(is.na(x), "NR", x))
test$RoomNum <- ifelse(is.na(test$RoomNum), -1, test$RoomNum)
test[, c("CryoSleep", "HomePlanet", "Destination","VIP", "Name")] <- 
  lapply(test[, c("CryoSleep", "HomePlanet", "Destination","VIP", "Name")], function (x) ifelse(is.na(x), "NR", x))

test$Age <- ifelse(is.na(test$Age), mean(na.omit(test$Age)), test$Age)



test <- mutate(test, across(c(HomePlanet,CryoSleep,Destination,VIP), factor))
test$InGroupId <- as.factor(test$InGroupId)
test$Deck <- as.factor(test$Deck)
test$Side <- as.factor(test$Side)
test$Side <- relevel(test$Side, ref = "P")
```

```{r}
test$route <- paste(test$HomePlanet, test$Destination)
test$route <- as.factor(test$route)
test <- separate(test, Name, into = c("FirstName", "LastName"), sep = " ")
test$LastName <- ifelse(is.na(test$LastName), "NR", test$LastName)
#test$family <- ifelse(duplicated(test$LastName) | duplicated(test$LastName, fromLast = TRUE), "Yes", "No")
test$Family <- ifelse(duplicated(test[, c("Group", "LastName")]) | 
                   duplicated(test[, c("Group", "LastName")], fromLast = TRUE), 
                   "Yes", "No")
test$Family <- as.factor(test$Family)

test$position <- as.factor(paste(test$Deck, test$Side))

```

```{r}
random.forest <- randomForest(Transported ~ .-FirstName-LastName -VIP-InGroupId-Deck-Side-HomePlanet-Destination-Family, data = st.data, ntree = 10000)
varImpPlot(random.forest)
pred <- predict(random.forest, type = 'class', newdata=test)

test$Transported <- pred

submission <- test[,c("PassengerId", "Transported")]
write.csv(submission, "submission.csv", row.names = FALSE)


```



```{r}


```